spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-gt0q8bdg.sql.tencentcdb.com:27950/ecareer?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Qinkang368
  redis:
    host: 124.221.157.240 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

minio:
  endpoint: http://124.221.157.240:9090
  bucketName: ecareer
  access-key: minioadmin
  secret-key: Josh@123

logging:
  level:
    root: info
    com.ecareer: debug